let todo = () => {
  exception Todo;
  raise(Todo);
};
